spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/secure_server_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

signature.key-store-path=classpath:secure-server-keystore.p12
signature.key-store-type=PKCS12
signature.key-store-password=changeit
signature.key-alias=secure-server
signature.key-password=changeit
signature.algorithm=SHA256withRSA